---
_extends: gh-labels

repository:
  name: ocis
  description: 'End-to-End Test Suite for the CS3 APIs'
  homepage: https://owncloud.dev/cs3api-validator/
  topics: reva, ocis, cs3Apis

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  
teams:
  - name: ci
    permission: admin
  - name: employees
    permission: push
  - name: cern
    permission: triage

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/drone/pr
      enforce_admins: null
      restrictions:
        apps: []
        users:
          - dependabot
        teams:
          - ci
          - employees
...
