---
depends_on:
  - test-acceptance-cs3api
  - lint

steps:
  - name: dryrun
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      auto_tag: true
      build_args:
        - REVISION=${CI_COMMIT_SHA}
        - VERSION=${CI_COMMIT_TAG=latest}
      dockerfile: docker/Dockerfile.multiarch
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: linux/amd64
      pull_image: false
      repo: opencloudeu/cs3api-validator,quay.io/opencloudeu/cs3api-validator
    when:
      - event: pull_request
  - image: woodpeckerci/plugin-docker-buildx:latest
    name: build-and-push
    settings:
      auto_tag: true
      build_args:
        - REVISION=${CI_COMMIT_SHA}
        - VERSION=${CI_COMMIT_TAG=latest}
      dockerfile: docker/Dockerfile.multiarch
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins:
        - password:
            from_secret: docker_password
          registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
        - password:
            from_secret: quay_password
          registry: https://quay.io
          username:
            from_secret: quay_username
      platforms: linux/amd64,linux/arm64
      pull_image: false
      repo: opencloudeu/cs3api-validator,quay.io/opencloudeu/cs3api-validator
    when:
      - event: tag
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
  - name: push-docker-readme
    image: chko/docker-pushrm:1
    environment:
      DOCKER_USER:
        from_secret: docker_username
      DOCKER_PASS:
        from_secret: docker_password
      PUSHRM_TARGET: opencloudeu/cs3api-validator
      PUSHRM_SHORT: Docker images for cs3api-validator
      PUSHRM_FILE: README.md
    when:
      - event: tag
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
  - name: push-quay-readme
    image: chko/docker-pushrm:1
    environment:
      APIKEY__QUAY_IO:
        from_secret: quay_apikey
      PUSHRM_TARGET: quay.io/opencloudeu/cs3api-validator
      PUSHRM_FILE: README.md
      PUSHRM_PROVIDER: quay
    when:
      - event: tag
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
when:
  - event: pull_request
  - event: tag
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
