---
depends_on:
  - test-acceptance-cs3api
  - lint

steps:
  - name: dryrun
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      auto_tag: true
      build_args:
        - REVISION=${CI_COMMIT_SHA}
        - VERSION=${CI_COMMIT_TAG=latest}
      dockerfile: docker/Dockerfile.multiarch
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: linux/amd64
      pull_image: false
      repo: opencloudeu/cs3api-validator,quay.io/opencloudeu/cs3api-validator
    when:
      - event: pull_request
  - image: woodpeckerci/plugin-docker-buildx:latest
    name: docker
    settings:
      auto_tag: true
      build_args:
        - REVISION=${CI_COMMIT_SHA}
        - VERSION=${CI_COMMIT_TAG=latest}
      dockerfile: docker/Dockerfile.multiarch
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins:
        - password:
            from_secret: docker_password
          registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
        - password:
            from_secret: quay_password
          registry: https://quay.io
          username:
            from_secret: quay_username
      platforms: linux/amd64,linux/arm64
      pull_image: false
      repo: opencloudeu/cs3api-validator,quay.io/opencloudeu/cs3api-validator
    when:
      - event: tag
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
when:
  - event: pull_request
  - event: tag
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
